### ISSUE TITLE
Application crashes silently with a Logitech MX master 2S

### ISSUE THREAD

**Issue by nicoulaj** [libratbag/piper#108]
```
Traceback (most recent call last):
  File "/usr/bin/piper", line 11, in <module>
    load_entry_point('piper==0.2.1', 'console_scripts', 'piper')()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 467, in main
    win = Piper()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 79, in __init__
    self._ratbag_device = self._fetch_ratbag_device()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 177, in _fetch_ratbag_device
    self._show_error("Device {} does not support switchable resolutions".format(d.description))
AttributeError: 'RatbagdDevice' object has no attribute 'description'
```

I guess there should be a catch-all to display unmanaged exception tracebacks as a GUI, otherwise it crashes without any feedback when launched from the OS menu in this case (exception raised in catch block).

Another issue is that running `piper --help` or `piper --version` crashes with the same traceback, so it seems argument parsing is done after the "real stuff".

 * ratbagd: 0.4
 * piper: 0.2.1

**Comment by Hjdskes** [comment]
Please use the latest commit from the master branch, for both Piper and libratbag.
