### ISSUE TITLE
Profiles are duplicated when going back to device selection and opening again.

### ISSUE THREAD

**Issue by cvuchener** [libratbag/piper#124]
When going back to device selection and opening the device again, the profiles are duplicated. Selecting a duplicated profile crashes piper.

```
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:472: Warning: gsignal.c:2563: instance '0x56393b9c6a80' has no handler with id '1315'
  GObjectModule.signal_handler_block(obj, handler_id)
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:452: Warning: gsignal.c:2605: instance '0x56393b9c6a80' has no handler with id '1315'
  GObjectModule.signal_handler_unblock(self.obj, self.handler_id)
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:472: Warning: gsignal.c:2563: instance '0x56393b9c6c80' has no handler with id '1316'
  GObjectModule.signal_handler_block(obj, handler_id)
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:452: Warning: gsignal.c:2605: instance '0x56393b9c6c80' has no handler with id '1316'
  GObjectModule.signal_handler_unblock(self.obj, self.handler_id)
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:472: Warning: gsignal.c:2563: instance '0x56393b9ba460' has no handler with id '1357'
  GObjectModule.signal_handler_block(obj, handler_id)
/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py:452: Warning: gsignal.c:2605: instance '0x56393b9ba460' has no handler with id '1357'
  GObjectModule.signal_handler_unblock(self.obj, self.handler_id)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/piper/resolutionrow.py", line 66, in _on_active_profile_changed
    self._init_values(resolution)
  File "/usr/local/lib/python3.6/site-packages/piper/resolutionrow.py", line 61, in _init_values
    self.scale.props.adjustment.configure(xres, minres, maxres, 50, 50, 0)
AttributeError: 'NoneType' object has no attribute 'configure'
```

**Comment by Hjdskes** [comment]
Thanks!
