### ISSUE TITLE
Ratbagdevice object has no attribute 'description'

### ISSUE THREAD

**Issue by kaymio** [libratbag/piper#128]
Ratbagd didn't start even when it was enabled in systemd.
Arch Linux x64, ratbagd = 0.4-1, piper = 0.2.1-2, libratbag 0.9-1, all from the AUR
When trying to start piper I get this:

`piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 11, in <module>
    load_entry_point('piper==0.2.1', 'console_scripts', 'piper')()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 467, in main
    win = Piper()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 79, in __init__
    self._ratbag_device = self._fetch_ratbag_device()
  File "/usr/lib/python3.6/site-packages/piper/__init__.py", line 177, in _fetch_ratbag_device
    self._show_error("Device {} does not support switchable resolutions".format(d.description))
AttributeError: 'RatbagdDevice' object has no attribute 'description'`

**Comment by Hjdskes** [comment]
See #108.
