### ISSUE TITLE
Crash when unplugging mouse

### ISSUE THREAD

**Issue by phomes** [libratbag/piper#191]
I had a mouse plugged in and opened on the buttons page. I unplugged the mouse and put in another. Piper crashed with:

Traceback (most recent call last):
  File "/home/phomes/piper/piper/window.py", line 129, in <lambda>
    self._present_welcome_perspective(ratbag.devices),
  File "/home/phomes/piper/piper/window.py", line 141, in _present_welcome_perspective
    welcome_perspective.set_devices(devices)
  File "/home/phomes/piper/piper/welcomeperspective.py", line 53, in set_devices
    self.add_device(device)
  File "/home/phomes/piper/piper/welcomeperspective.py", line 60, in add_device
    self.listbox.add(DeviceRow(device))
  File "/home/phomes/piper/piper/devicerow.py", line 41, in __init__
    self.title.set_text(device.name)
TypeError: Argument 1 does not allow None as a value

**Comment by whot** [comment]
I can't seem to reproduce that. Do you get any errors on the libratbag side?

**Comment by phomes** [comment]
I cannot reproduce either. I did not notice anything in libratbag's output.

**Comment by whot** [comment]
I wonder if it's a race condition that got triggered somehow. Not getting the device name usually means that the device didn't initialize correctly, but no idea what could've caused that.

Closing for now, please re-open when we reproduce it
