### ISSUE TITLE
piper fails with ModuleNotFoundError: No module named 'evdev'

### ISSUE THREAD

**Issue by sheepdestroyer** [libratbag/piper#198]
Following the instructions to build both ratbagd and piper, i get the followin error when trying to run it on fedora 27 : 

````
[sheepdestroyer@sheepora-X230 libratbag]$ sudo systemctl status ratbagd.service
[sudo] password for sheepdestroyer: 
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-11-21 14:48:13 JST; 6min ago
 Main PID: 23701 (ratbagd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ratbagd.service
           └─23701 /usr/bin/ratbagd

nov. 21 14:48:13 sheepora-X230 systemd[1]: Starting Daemon to introspect and modify configurable mice...
nov. 21 14:48:13 sheepora-X230 systemd[1]: Started Daemon to introspect and modify configurable mice.

[sheepdestroyer@sheepora-X230 libratbag]$ piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 17, in <module>
    from .ratbagd import Ratbagd, RatbagdDBusUnavailable
  File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 28, in <module>
    from evdev import ecodes
ModuleNotFoundError: No module named 'evdev'
[sheepdestroyer@sheepora-X230 libratbag]$ 
````

**Comment by whot** [comment]
dnf install python3-evdev
