### ISSUE TITLE
GTK-Critical fault during start

### ISSUE THREAD

**Issue by Cogitri** [libratbag/piper#200]
Hello,

I currently get this error when I try to start piper:
`(piper:8580): Gtk-CRITICAL **: Unable to retrieve object 'stack' from class template for type 'Window' while building a 'Window'
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/piper/window.py", line 52, in __init__
    self.init_template()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/piper/gi_composites.py", line 101, in <lambda>
    cls.init_template = lambda s: _init_template(s, cls, base_init_template)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/piper/gi_composites.py", line 131, in _init_template
    ', '.join(self.__gtemplate_widgets__))
AttributeError: A missing child widget was set using GtkTemplate.Child and the entire template is now broken (widgets: stack, add_profile_button, listbox_profiles, label_profile, notification_commit)`

Related package versions:

`$ python3 -V
Python 3.6.3`

`$ gtk-launch --version
3.22.26`

**Comment by Hjdskes** [comment]
Are you on an up-to-date master branch? Try re-building the project as a whole. It works fine for me here.

**Comment by Cogitri** [comment]
Oh, sorry, it seems like that was a mistake on my side, meson doesn't have a `pythondir` option or something like that, so I gotta edit the `meson.build` file for it to install python files into `/usr/x86_64-pc-linux-gnu/lib/python3.6` instead of `/usr/lib/python3.6`, seems like my sed silently failed to pick that up. Sorry again and thanks for the great project! :)
