### ISSUE TITLE
 0.2.900: _on_device_selected crashes with TypeError

### ISSUE THREAD

**Issue by el-dom** [libratbag/piper#204]
I'm using Python 3.6.4. When opening piper and selecting my device (Logitech G403 wireless) it crashes with the following stacktrace

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 169, in _on_device_selected
    self._present_mouse_perspective(device)
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 86, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 67, in __init__
    self._init_ui()
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 84, in _init_ui
    row = ResolutionRow(self._device, resolution)
  File "/usr/lib/python3.6/site-packages/piper/resolutionrow.py", line 49, in __init__
    self._init_values(resolution)
  File "/usr/lib/python3.6/site-packages/piper/resolutionrow.py", line 69, in _init_values
    self.scale.props.adjustment.configure(xres, minres, maxres, 50, 50, 0)
TypeError: Argument 2 does not allow None as a value
```
https://github.com/libratbag/piper/blob/master/piper/window.py#L169 uses only one argument to call `_present_mouse_perspective`

Device info for the sake of completeness
```
ratbagctl info event18
event18 - Logitech G403 Prodigy Wired/Wireless Gaming Mouse
               SVG: /usr/share/libratbag/gnome/logitech-g403.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, disable-profile, button, button-keys, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 800dpi @ 1000Hz (default)
    1: 1000dpi @ 1000Hz
    2: 1200dpi @ 1000Hz
    3: 1600dpi @ 1000Hz (active)
    4: 6800dpi @ 1000Hz
  Button: 0 type unknown is mapped to 'button 1'
  Button: 1 type unknown is mapped to 'button 2'
  Button: 2 type unknown is mapped to 'button 3'
  Button: 3 type unknown is mapped to 'button 4'
  Button: 4 type unknown is mapped to 'button 5'
  Button: 5 type unknown is mapped to 'resolution-cycle-up'
  LED: 0 type: logo, depth: rgb, mode: breathing, color: 002aff, duration: 5000, brightness: 73
  LED: 1 type: side, depth: rgb, mode: breathing, color: 002aff, duration: 5000, brightness: 73
Profile 1: (disabled)
Profile 2: (disabled)
```

**Comment by Hjdskes** [comment]
Are you using the latest versions of both Piper and libratbag?

**Comment by el-dom** [comment]
As of now, i'm using 0.9.901 of lib ratbag and 0.2.900 of piper. Installed via https://aur.archlinux.org/packages/piper/

**Comment by Hjdskes** [comment]
Can you try the latest master of both Piper and libratbag? There have been quite some changes since the releases.

**Comment by el-dom** [comment]
Strike! I've built and installed the master and piper starts flawlessly. So whatever was causing it is already fixed in the upcoming release. Thank you for your support. I'm closing this.
