### ISSUE TITLE
TypeError upon startup (minres is None)

### ISSUE THREAD

**Issue by RipCazza** [libratbag/piper#210]
Hello dear maintainer,

Running Piper on Arch Linux throws an error at startup.

- Piper 0.2.900-5 from AUR
- libratbagd 0.9.902 from AUR
- Logitech G700s - Logitech HID++1.0 (however, same error with mouse plugged out)

Trying to run it gives the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 86, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 67, in __init__
    self._init_ui()
  File "/usr/lib/python3.6/site-packages/piper/resolutionspage.py", line 84, in _init_ui
    row = ResolutionRow(self._device, resolution)
  File "/usr/lib/python3.6/site-packages/piper/resolutionrow.py", line 49, in __init__
    self._init_values(resolution)
  File "/usr/lib/python3.6/site-packages/piper/resolutionrow.py", line 69, in _init_values
    self.scale.props.adjustment.configure(xres, minres, maxres, 50, 50, 0)
TypeError: Argument 2 does not allow None as a value
```

Ratbag itself seems to be running as it should.

The same issue is mentioned in #166. However, the thread mentioned that #186 should fix it. It hasn't for me. #208 also seems related, but the issue is poorly written.

Thanks for your time and effort!

**Comment by Amosar** [comment]
Try the git version it work for me https://aur.archlinux.org/packages/piper-git/

**Comment by RipCazza** [comment]
Switching to the git version seems to have solved the issue for me, even though it seems I can't get macros to work for my various buttons. Either way, thank you for the help!

**Comment by Hjdskes** [comment]
> even though it seems I can't get macros to work for my various buttons.

Can you open a separate issue for this?

**Comment by RipCazza** [comment]
https://github.com/libratbag/libratbag/issues/486

Opened a new issue. Thanks!
