### ISSUE TITLE
PPA for Ubuntu 18.04

### ISSUE THREAD

**Issue by muzena** [libratbag/piper#211]
Ratbag and Piper [PPA repository](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/ratbag-piper)

**Comment by muzena** [comment]
In About dialog, Close button does not work.

**Comment by benpicco** [comment]
I've installed piper from the ppa on Kubuntu 18.04, but when I try to run it I get

```
(piper:1437): Gtk-WARNING **: 20:11:22.278: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:1437): Gtk-WARNING **: 20:11:22.279: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:1437): Gtk-WARNING **: 20:11:22.279: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3/dist-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3/dist-packages/piper/mouseperspective.py", line 88, in set_device
    self.stack.add_titled(ButtonsPage(device), "buttons", _("Buttons"))
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 50, in __init__
    self._set_profile(self._device.active_profile)
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 58, in _set_profile
    self._on_ratbagd_button_action_type_changed(ratbagd_button, None, button)
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 86, in _on_ratbagd_button_action_type_changed
    label = _(RatbagdButton.SPECIAL_DESCRIPTION[ratbagd_button.special])
KeyError: 4294967295
```

**Comment by Hjdskes** [comment]
This (unofficial) PPA is supplying an older version of Piper, which does not yet contain the fix for this. If you build Piper from source, you shouldn't run into this issue.

**Comment by whot** [comment]
fwiw, last commit in piper git is a16c1de34cb379d5cc5bbc7d84c55a7f483e83e4 from two weeks ago

**Comment by muzena** [comment]
@benpicco 
Try now, I update ppa with version: '0.2.901'

**Comment by benpicco** [comment]
@muzena the warning is gone, but it still crashes immediately:
```
% ratbagctl 
event2:    Logitech Gaming Mouse G502
% piper
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3/dist-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3/dist-packages/piper/mouseperspective.py", line 88, in set_device
    self.stack.add_titled(ButtonsPage(device), "buttons", _("Buttons"))
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 50, in __init__
    self._set_profile(self._device.active_profile)
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 58, in _set_profile
    self._on_ratbagd_button_action_type_changed(ratbagd_button, None, button)
  File "/usr/lib/python3/dist-packages/piper/buttonspage.py", line 86, in _on_ratbagd_button_action_type_changed
    label = _(RatbagdButton.SPECIAL_DESCRIPTION[ratbagd_button.special])
KeyError: 4294967295
```

I'll try building it from source and see how that goes.

**Comment by thparamboll** [comment]
see libratbag/libratbag#281

**Comment by phomes** [comment]
see libratbag/libratbag#281
