### ISSUE TITLE
Run file GI error

### ISSUE THREAD

**Issue by ConnerFrancis** [libratbag/piper#231]
Trying to get my G502 to work with Piper. After building libratbag and piper with no errors using git clones, setting up the daemon, etc. I was ready to run `./piper.in`, however I got this error:

```
  File "./piper.in", line 11
    if gtk_version < (@gtk_major_version@, @gtk_minor_version@):
                      ^
SyntaxError: invalid syntax
```

I am most definitely a python `n00b` and am probably missing something obvious. Anything I can do to fix this?

**Comment by ConnerFrancis** [comment]
I tried that, but I got this error when running `builddir/piper.devel`:

```
Running from source tree, using local files
Traceback (most recent call last):
  File "./piper.devel", line 39, in <module>
    from piper.application import Application
  File "/home/conner/piper/piper/application.py", line 17, in <module>
    from .ratbagd import Ratbagd, RatbagdDBusUnavailable
  File "/home/conner/piper/piper/ratbagd.py", line 28, in <module>
    from evdev import ecodes
ModuleNotFoundError: No module named 'evdev'
```

I uninstalled and reinstalled libevdev by compiling from their source, same error :(

**Comment by ConnerFrancis** [comment]
Nevermind fellas, found the solution. I ran `python3.6 /usr/bin/pip install --user evdev` since my `pip` was set to python version `2.7` instead of `3.6`. So, `evdev` was in the `2.7` package dist folder.
