### ISSUE TITLE
Can't set button to "invalid"

### ISSUE THREAD

**Issue by ideal-fire** [libratbag/piper#241]
I want to unbind a button so I'm trying to set it to "invalid," but it crashes with this terminal error when I click apply in the "configure button 4" menu:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gi/_propertyhelper.py", line 426, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3.7/site-packages/piper/ratbagd.py", line 779, in special
    self._set_dbus_property("SpecialMapping", "u", special)
  File "/usr/lib/python3.7/site-packages/piper/ratbagd.py", line 178, in _set_dbus_property
    val = GLib.Variant("{}".format(type), value)
  File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 172, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
OverflowError: -1 not in range 0 to 4294967295
```

Distro: Arch
Mouse: G502
piper version: latest git, 5fbeacc447ea6f3f6795b61ce89e557313606e4d
libratbag version: latest git, 23ff4e753d68267096ea66e729337bb3653fc650

**Comment by whot** [comment]
So, aside from the crash itself, the value "invalid" shouldn't be set-able because it indicates that it's a value libratbag doesn't understand. This is a bug that we should fix in piper and it'll fix the crash too.

**Comment by whot** [comment]
> Should we provide an option to unbind buttons?

yeah, I think that'd be a useful thing. I think setting it to button 0 or so
should work anyway (in libratbag) but we should have this as a specific
entry in piper.
