### ISSUE TITLE
DBus.Error.NameHasNoOwner

### ISSUE THREAD

**Issue by YoyPa** [libratbag/piper#300]
Hello,
I get the following error from piper when I launch it from terminal:
```GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.527" does not exist```
Here are dbus related log from journalctl, or see full log at the bottom:
```
févr. 09 18:06:42 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:42 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:44 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:44 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
```
A hint at where to look could be helpfull

Piper and libratbag are installed from arch repo and version are:
```
Name                     : libratbag
Version                  : 0.9.904-1

Name                     : piper
Version                  : 0.2.903-1
```

Mouse is:
```
Bus 001 Device 012: ID 046d:c06b Logitech, Inc. G700 Wireless Gaming Mouse
```

full log:
```
févr. 09 18:06:38 yo-gs kwin_x11[1357]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 37120, resource id: 117440519, major code: 15 (QueryTree), minor code: 0
févr. 09 18:06:42 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:42 yo-gs systemd[1]: Starting Daemon to introspect and modify configurable mice...
févr. 09 18:06:42 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:42 yo-gs systemd[1]: Started Daemon to introspect and modify configurable mice.
févr. 09 18:06:42 yo-gs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:42 yo-gs kernel: audit: type=1130 audit(1549732002.478:178): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs kernel: audit: type=1131 audit(1549732003.185:179): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:43 yo-gs systemd[1]: Starting Daemon to introspect and modify configurable mice...
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:43 yo-gs systemd[1]: Started Daemon to introspect and modify configurable mice.
févr. 09 18:06:43 yo-gs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs kernel: audit: type=1130 audit(1549732003.198:180): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:43 yo-gs kernel: audit: type=1131 audit(1549732003.865:181): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs systemd[1]: Starting Daemon to introspect and modify configurable mice...
févr. 09 18:06:43 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:43 yo-gs systemd[1]: Started Daemon to introspect and modify configurable mice.
févr. 09 18:06:43 yo-gs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:43 yo-gs kernel: audit: type=1130 audit(1549732003.875:182): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:44 yo-gs audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:44 yo-gs dbus-daemon[685]: [system] Activating via systemd: service name='org.freedesktop.ratbag1' unit='ratbagd.service' requested by ':1.526' (uid=1000 pid=20741 comm="python3 /usr/bin/piper ")
févr. 09 18:06:44 yo-gs systemd[1]: Starting Daemon to introspect and modify configurable mice...
févr. 09 18:06:44 yo-gs kernel: audit: type=1131 audit(1549732004.538:183): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:44 yo-gs dbus-daemon[685]: [system] Successfully activated service 'org.freedesktop.ratbag1'
févr. 09 18:06:44 yo-gs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:44 yo-gs kernel: audit: type=1130 audit(1549732004.548:184): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:44 yo-gs systemd[1]: Started Daemon to introspect and modify configurable mice.
févr. 09 18:06:45 yo-gs audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:45 yo-gs kernel: audit: type=1131 audit(1549732005.215:185): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ratbagd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
févr. 09 18:06:51 yo-gs kwin_x11[1357]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 38717, resource id: 117440519, major code: 15 (QueryTree), minor code: 0
```

**Comment by Hjdskes** [comment]
Does configuring the mouse work with `ratbagctl`?

**Comment by YoyPa** [comment]
No, I can just get not set, info is also not working.
```
$ ratbagctl list
event7:    Logitech G700 Laser Mouse
-----------------------------------------------------------------------------------------------------------------------
$ ratbagctl info event7
GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.14599" does not exist
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2564, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2558, in main
    f(r, cmd)
  File "/usr/bin/ratbagctl", line 1290, in show_device
    print_device(d, 0)
  File "/usr/bin/ratbagctl", line 1270, in print_device
    with d.get_svg_fd('gnome') as fd:
  File "/usr/bin/ratbagctl", line 401, in get_svg_fd
    fd = self._dbus_call_return_one_fd("GetSvgFd", "s", theme)
  File "/usr/bin/ratbagctl", line 233, in _dbus_call_return_one_fd
    2000, None, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.14599" does not exist (3)
-----------------------------------------------------------------------------------------------------------------------
$ ratbagctl profile 0 name get event7
Yo
-----------------------------------------------------------------------------------------------------------------------
$ ratbagctl profile 0 name set choucroute event7
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gi/_propertyhelper.py", line 404, in obj_set_property
    prop.fset(self, value)
  File "/usr/bin/ratbagctl", line 491, in name
    self._set_dbus_property("Name", "s", name)
  File "/usr/bin/ratbagctl", line 190, in _set_dbus_property
    2000, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.14641" does not exist (3)
GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.14641" does not exist
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 2564, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ratbagctl", line 2558, in main
    f(r, cmd)
  File "/usr/bin/ratbagctl", line 1530, in func_profile_name_set
    commit(d, args)
  File "/usr/bin/ratbagctl", line 1625, in commit
    device.commit()
  File "/usr/bin/ratbagctl", line 423, in commit
    self._dbus_call("Commit", "")
  File "/usr/bin/ratbagctl", line 208, in _dbus_call
    2000, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name ":1.14641" does not exist (3)
```

**Comment by Hjdskes** [comment]
Then it's not a Piper issue. It could be a libratbag/ratbagd issue or an issue with your system. From the logs, it looks like something is stopping ratbagd (the lines with `audit[1]: SERVICE_STOP`), but I don't know what this is. @whot Any idea maybe?

**Comment by whot** [comment]
[selinux](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sec-audit_record_types) is where the `SERVICE_STOP` comes from.

ratbagd has auto-shutdown now but it's 20min, not a few seconds so the only reason the message would be triggered is either ratbagd crashing (should show up in the journal) or SELinux preventing it. Given the message above, I'd say the latter is the issue but that requires local debugging on your machine. Maybe running `restorecon` on the various files installed by libratbag may be enough, otherwise start [selinux troubleshooting](https://fedoramagazine.org/troubleshooting-selinux/). I don't know a specific answer to this issue here though, so we'd both just be googling around. Given you see the errors, it's going to be much more efficient if you do the googling ;)

**Comment by YoyPa** [comment]
I tested ratbagctl on Manjaro, Antergos and Fedora ISOs and I had same error on all of them.
I just found what caused the issue:
G700 default profile's names are (at least on mine) ```Profile n° x``` (x from 1 to 5 incl.).
The ```°``` is not handled correctly and cause the error even if the profile is disabled (unticked in logitech software).

PS: Do you want me to reopen the issue on the correct repo ? :innocent:

**Comment by whot** [comment]
Oh, that looks like a libratbag bug then, please open a bug there. Ideally, try `sudo ./build/ratbag-command` from the build directory, that should give us a better backtrace then.
