### ISSUE TITLE
Piper fails to start with GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Unknown method 'GetSvgFd' or interface 'org.freedesktop.ratbag1.Device'.

### ISSUE THREAD

**Issue by NamelessVoice** [libratbag/piper#312]
I decided to try Ratbag + Piper, in Linux Mint 19.1.
Installed the PPA and installed ratbag and Piper from it.

Ratbag version 0.9.905 appears to be installed okay, but Piper crashes immediately on startup.
Piper version is 0.2.902-0-201902190516~ubuntu18.04.1.
Running it from the desktop does nothing, while running it from the terminal gives the following error:

```
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Unknown method 'GetSvgFd' or interface 'org.freedesktop.ratbag1.Device'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 71, in __init__
    self._present_welcome_perspective(ratbag.devices)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 138, in _present_welcome_perspective
    welcome_perspective.set_devices(devices)
  File "/usr/lib/python3/dist-packages/piper/welcomeperspective.py", line 53, in set_devices
    self.add_device(device)
  File "/usr/lib/python3/dist-packages/piper/welcomeperspective.py", line 60, in add_device
    self.listbox.add(DeviceRow(device))
  File "/usr/lib/python3/dist-packages/piper/devicerow.py", line 43, in __init__
    fd = device.get_svg_fd("gnome")
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 405, in get_svg_fd
    fd = self._dbus_call_return_one_fd("GetSvgFd", "s", theme)
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 231, in _dbus_call_return_one_fd
    2000, None, None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Unknown method 'GetSvgFd' or interface 'org.freedesktop.ratbag1.Device'. (19)
```

I wonder if it's related to but #299, but that one has absolutely no debug info, so I can't really tell.

**Comment by whot** [comment]
yeah, you need piper 0.2.904 because that's the only one with the new API updates. Was released yesterday so hopefully it'll show up in the PPA soon.

**Comment by NamelessVoice** [comment]
Okay, that version of Piper has finally shown up in the PPA and the problem is now resolved.

Seems a bit strange that the two versions got out of sync for so long when they are so interdependent.

**Comment by Hjdskes** [comment]
That isn't up to us. Someone else is packaging Piper and libratbag and maintaining the PPA. We just release new versions, and then it's up to the packagers to update their packages.
