### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by reversondias** [libratbag/piper#351]
When I ran piper I received this stack error:

No active profile. Please report this bug to the libratbag developers
No active profile. Please report this bug to the libratbag developers
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 69, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3/dist-packages/piper/window.py", line 147, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3/dist-packages/piper/mouseperspective.py", line 90, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3/dist-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/usr/lib/python3/dist-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/usr/lib/python3/dist-packages/piper/mousemap.py", line 111, in __init__
    svg_bytes = get_svg(ratbagd_device.model)
  File "/usr/lib/python3/dist-packages/piper/svg.py", line 32, in get_svg
    if model.startswith('usb:') or model.startswith('bluetooth:'):
AttributeError: 'NoneType' object has no attribute 'startswith'

I use Ubuntu Ubuntu 18.04.2 LTS
And install piper using PPA repository (libratbag-piper/piper-libratbag-git).
Piper version:  0.2.904-201905281409~ubuntu18.04.1
ratbagd version: Version: 0.4-3

I compared the last version code files with the before one and apparently  not changed. 
Someone can help me?

**Comment by whot** [comment]
>  ratbagd version: Version: 0.4-3

this needs to be v0.9.905, otherwise the two won't be compatible. 0.4 is 2 years old, not a good time for something that's effectively still alpha/beta software.

**Comment by YaMoef** [comment]
i had the same issue did this and it worked for me
`sudo add-apt-repository ppa:trebelnik-stefina/ratbag-piper`
`sudo apt-get update`
`sudo apt-get install ratbagd`
`sudo apt-get install piper`

**Comment by whot** [comment]
unfortunately, the ubuntu packages are too old and don't get updated, not much we can do here as upstream project. Closing based on @YaMoef 's experience, getting ratbagd from the same PPA as piper should fix things.
