### ISSUE TITLE
Crash due to duplicate section in svg-lookup.ini file

### ISSUE THREAD

**Issue by ivergara** [libratbag/piper#366]
I just installed piper via the PAA in Ubuntu 19.04 and when trying to execute `piper` I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib/python3/dist-packages/piper/window.py", line 69, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib/python3/dist-packages/piper/window.py", line 147, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib/python3/dist-packages/piper/mouseperspective.py", line 90, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib/python3/dist-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/usr/lib/python3/dist-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/usr/lib/python3/dist-packages/piper/mousemap.py", line 111, in __init__
    svg_bytes = get_svg(ratbagd_device.model)
  File "/usr/lib/python3/dist-packages/piper/svg.py", line 27, in get_svg
    config.read_string(data.decode('utf-8'), source='svg-lookup.ini')
  File "/usr/lib/python3.7/configparser.py", line 722, in read_string
    self.read_file(sfile, source)
  File "/usr/lib/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/usr/lib/python3.7/configparser.py", line 1065, in _read
    lineno)
configparser.DuplicateSectionError: While reading from 'svg-lookup.ini' [line 29]: section 'Logitech G403' already exists
```

**Comment by whot** [comment]
This was fixed with #367 I think
