### ISSUE TITLE
apt install from ppa fails post_install on ubuntu 20.04

### ISSUE THREAD

**Issue by AvverbioPronome** [libratbag/piper#473]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.13
- Piper version: 0.4-1
- Distribution: Ubuntu 20.04
- Kernel version (ex. `uname -srmo`): `Linux 5.4.0-12-generic x86_64 GNU/Linux`

**Describe the bug**
```
E: py3compile:183: cannot create directory /usr/lib/python3/dist-packages/piper/__pycache__: FileNotFoundError(2, 'No su
ch file or directory')
Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 197, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 142, in compile
    source_bytes = loader.get_data(file)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/application.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/py_compile.py", line 218, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/py_compile.py", line 204, in main
    if quiet < 2:
NameError: name 'quiet' is not defined
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/__init__.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/application.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/buttondialog.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/buttonspage.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/devicerow.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/errorperspective.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/gi_composites.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/leddialog.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/ledspage.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/mousemap.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/mouseperspective.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/optionbutton.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/profilerow.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/ratbagd.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/resolutionrow.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/resolutionspage.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/svg.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/welcomeperspective.py'
[Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/piper/window.py'
dpkg: errore nell'elaborare il pacchetto piper (--configure):
 il sottoprocesso installato pacchetto piper script post-installation ha restituito lo stato di errore 1
Si sono verificati degli errori nell'elaborazione:
 piper
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

1. run `apt install piper`

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**

**Comment by AvverbioPronome** [comment]
It looks like my `/usr/lib/python3` is a symbolic link to python3.7, while piper runs with python3.8

**Comment by AvverbioPronome** [comment]
(however, flatpack version works fine with ratbagd from ppa)

**Comment by whot** [comment]
looks like a broken python installation tbh, the `/usr/lib/python3.8/py_compile.py` which complains about the `NameError` is not part of piper but the python install itself. Upstream bug: https://bugs.python.org/issue38731
