### ISSUE TITLE
piper crash when ratbagd isn't available

### ISSUE THREAD

**Issue by whot** [libratbag/piper#49]
When ratbagd isn't running, piper crashes instead of showing me a nice dialog. This is commit  afdadb691f76 on your buttons branch

```
$> n install && /opt/libratbag/bin/piper 
[0/1] Installing files.
Installing subdir /home/whot/code/ratbag/piper/piper to /opt/libratbag/lib/python3.6/site-packages
Installing data/piper.gresource to /opt/libratbag/share/piper/piper.gresource
Installing /home/whot/code/ratbag/piper/data/org.freedesktop.Piper.desktop to /opt/libratbag/share/applications
Installing /home/whot/code/ratbag/piper/data/org.freedesktop.Piper.svg to /opt/libratbag/share/icons/hicolor/scalable/apps
Installing /home/whot/code/ratbag/piper/build/piper to /opt/libratbag/bin
Running custom install script '/usr/bin/env sh /home/whot/code/ratbag/piper/meson_install.sh'
gtk-update-icon-cache: Cache file created successfully.
Traceback (most recent call last):
  File "/opt/libratbag/lib/python3.6/site-packages/piper/application.py", line 53, in do_activate
    window = Window(self._ratbag, application=self)
  File "/opt/libratbag/lib/python3.6/site-packages/piper/window.py", line 51, in __init__
    self._device = self._fetch_ratbag_device()
  File "/opt/libratbag/lib/python3.6/site-packages/piper/window.py", line 67, in _fetch_ratbag_device
    if len(self._ratbag.devices) == 0:
AttributeError: 'NoneType' object has no attribute 'devices'
```

**Comment by Hjdskes** [comment]
Fixed by #55.
