### ISSUE TITLE
Cannot build Piper: ModuleNotFoundError: No module named 'mesonbuild'

### ISSUE THREAD

**Issue by croraf** [libratbag/piper#571]
**Information**

- `ratbagd` version (`ratbagd --version`):
- Piper version: 97e56c9 (latest master)
- Distribution: Ubuntu 20.04
- Device: OMEN by HP 17-cb0014nm
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-45-generic x86_64 GNU/Linux

**Describe the bug**

I'm following the build instructions from the README.md but cannot build

**To Reproduce**

1. https://github.com/libratbag/piper#building-piper-from-git
2. On doing the third step of these
```
$ git clone https://github.com/libratbag/piper.git
$ cd piper
$ meson builddir --prefix=/usr/
```

3. The error happens
```
piper$ meson builddir --prefix=/usr/
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 6, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
 
```

**Additional context**
I tried with sudo also.

**Comment by FFY00** [comment]
Your meson installation is broken.

**Comment by Meriemi-git** [comment]
I have the same problem, i tried to reinstall meson module with `pip install --force-reinstall meson` but it doesn't work.
To bypass this error i run the command  `meson install --no-rebuild` inside the builddir directory.

**Comment by Meriemi-git** [comment]
I have the same problem, i try to reinstall meson with pip but it doesn't work.
The problem is coming from the permissions to install piper and the PATH to locate the meson module.
I finally managed to install piper with a dirty workaround by adding `/home/my_non_root_user/.local/bin/` to the .profile of root  but the problem has just been deported, now when i try to launch piper i have the following error : 
`ModuleNotFoundError: No module named 'piper'`

**Comment by muzena** [comment]
@croraf 
A da probaš instalirat iz [PPA repozitorija](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git)?

**Comment by Meriemi-git** [comment]
I try to install via PPA ans also via Flatpack but nothing works. That's why a try to build form sources.

**Comment by croraf** [comment]
@muzena It is working. Thank you. Hvala.

**Comment by muzena** [comment]
@Meriemi-git 
I using it on Ubuntu 20.04 and Linux Mint 20 and it works for me.
[Launchpad build system](https://launchpadlibrarian.net/498439083/buildlog_ubuntu-focal-amd64.piper_0.5.1+git448-97e56c9-202009211725~ubuntu20.04.1_BUILDING.txt.gz) build it without error.
I think that you have some install dependency problem.

**Comment by Meriemi-git** [comment]
@muzena What is Launchpad build system ?

**Comment by muzena** [comment]
@Meriemi-git 
It builds Debian packages for [Launchpad PPAs](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git)
It is defined through [build recipes](https://code.launchpad.net/~libratbag-piper/+recipe/piper)

**Comment by LuisDiazUgena** [comment]
Hi!

Sorry for resurrecting this old topic.  I'm using chachyOS and I'm trying to install piper on the system and I'm facing the same issue as described here.

What I have done is install gcc and meson using:

```
sudo pacman -S gcc
sudo pacman -S meson
```

Then rebooted and followed the instructions, cloned repo moved into folder and executed:

```
meson builddir --prefix=/usr/
```

And I'm getting the same error as described in this issue:

```
Traceback (most recent call last):
  File "/usr/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'

```

I have tried to unistall and reinstall meson and I still get the same error. 

```
which meson
/usr/bin/meson
```

would someone provide further instructions on how to fix the meson install? I got no errors on the command line after installing it usin pacman. Thanks.

EDIT:

found a way to isntall that seems to work:

```
sudo pacman -Syu meson
```
