### ISSUE TITLE
UBUNTU instalation not working

### ISSUE THREAD

**Issue by FilipeCunha720** [libratbag/piper#589]
### Steps to install:
```
$ git clone https://github.com/libratbag/piper.git
$ cd piper
$ meson builddir --prefix=/usr/
```
This fails because I don't have `meson`, so I [installed](https://mesonbuild.com/Getting-meson.html) `meson` 

`
pip3 install meson`

to run `meson` on piper directory I need to do this 

`
~/.local/bin/meson builddir --prefix=/usr/` 

This is the console output

```
The Meson build system
Version: 0.55.3
Source dir: /home/user/Documents/piper
Build dir: /home/user/Documents/piper/builddir
Build type: native build
Project name: piper
Project version: 0.5.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency pygobject-3.0 found: NO (tried pkgconfig)

meson.build:15:0: ERROR: Dependency "pygobject-3.0" not found, tried pkgconfig
```
So I installed `cmake` and `pygobject-3.0`

```

$ sudo apt-get install cmake

$ sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
```

When I run `meson` again I get another error.

```

The Meson build system
Version: 0.55.3
Source dir: /home/user/Documents/piper
Build dir: /home/user/Documents/piper/builddir
Build type: native build
Project name: piper
Project version: 0.5.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency pygobject-3.0 found: NO (tried pkgconfig and cmake)

meson.build:15:0: ERROR: Dependency "pygobject-3.0" not found, tried pkgconfig and cmake
```

So I assumed something was wrong with the installation of `pygobject-3.0`, I tried to install it again and this was the output.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.36.0-1).
python3-gi-cairo is already the newest version (3.36.0-1).
python3-gi-cairo set to manually installed.
gir1.2-gtk-3.0 is already the newest version (3.24.20-0ubuntu1).
gir1.2-gtk-3.0 set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 51 not to upgrade.
```

And now I'm stuck, what am I missing?

**Comment by kleboldrina** [comment]
install python-gi-dev, ratbagd, flake8.

**Comment by FilipeCunha720** [comment]
Thanks, @kleboldrina that worked.

I ran this command:

`sudo apt install python-gi-dev ratbagd flake8`

**I got this output:**

```
The Meson build system
Version: 0.55.3
Source dir: /home/filipecunha/Documents/piper
Build dir: /home/filipecunha/Documents/piper/builddir
Build type: native build
Project name: piper
Project version: 0.5.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency pygobject-3.0 found: YES 3.36.0
Program ratbagd found: YES
Message: 
    *********************** WARNING ****************************
    *                 (   )(                                   *
    *         (\-.     ) (  )    ratbagd found in $PATH is too *
    *         / _`> .---------.  old and  will  not  work with *
    * _)     / _)=  |'-------'|  this version of Piper. Please *
    *(      / _/    |O   O   o|  update libratbag/ratbagd.     *
    * `-.__(___)_   | o O . o |                                *
    ************************************************************
    
Configuring piper.1 using configuration
Configuring AboutDialog.ui using configuration
WARNING: Gettext not found, all translation targets will be ignored.
Configuring org.freedesktop.Piper.appdata.xml.in using configuration
Program svgs/check-svg.py found: YES
Program svg-lookup-ini-test.py found: YES
Program check-svg-in-meson.build.sh found: YES
Program check-files-in-git.sh found: YES
Configuring piper.gresource.xml with command
Found pkg-config: /usr/bin/pkg-config (0.29.1)
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.46.0': Python Module.
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.51.0': modules arg in python.find_installation.
Program python3 (lxml, evdev, cairo, gi) found: NO modules: evdev, cairo, gi

meson.build:82:8: ERROR: python is missing modules: lxml

```

I installed `lxml`

`pip3 install lxml`

**got this output**

```
The Meson build system
Version: 0.55.3
Source dir: /home/filipecunha/Documents/piper
Build dir: /home/filipecunha/Documents/piper/builddir
Build type: native build
Project name: piper
Project version: 0.5.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency pygobject-3.0 found: YES 3.36.0
Program ratbagd found: YES
Message: 
    *********************** WARNING ****************************
    *                 (   )(                                   *
    *         (\-.     ) (  )    ratbagd found in $PATH is too *
    *         / _`> .---------.  old and  will  not  work with *
    * _)     / _)=  |'-------'|  this version of Piper. Please *
    *(      / _/    |O   O   o|  update libratbag/ratbagd.     *
    * `-.__(___)_   | o O . o |                                *
    ************************************************************
    
Configuring piper.1 using configuration
Configuring AboutDialog.ui using configuration
WARNING: Gettext not found, all translation targets will be ignored.
Configuring org.freedesktop.Piper.appdata.xml.in using configuration
Program svgs/check-svg.py found: YES
Program svg-lookup-ini-test.py found: YES
Program check-svg-in-meson.build.sh found: YES
Program check-files-in-git.sh found: YES
Configuring piper.gresource.xml with command
Found pkg-config: /usr/bin/pkg-config (0.29.1)
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.46.0': Python Module.
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.51.0': modules arg in python.find_installation.
Program python3 (lxml, evdev, cairo, gi) found: YES (/usr/bin/python3) modules: lxml, evdev, cairo, gi
Configuring piper using configuration
Configuring piper.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/filipecunha/Documents/piper/meson_install.sh)
Program flake8 found: YES
Build targets in project: 1
WARNING: Project specifies a minimum meson_version '>= 0.42.0' but uses features which were added in newer versions:
 * 0.46.0: {'Python Module'}
 * 0.51.0: {'modules arg in python.find_installation'}


ERROR: Could not detect Ninja v1.7 or newer
```

I installed `ninja`


`sudo apt-get install ninja-build`

**and got this output**

```

The Meson build system
Version: 0.55.3
Source dir: /home/filipecunha/Documents/piper
Build dir: /home/filipecunha/Documents/piper/builddir
Build type: native build
Project name: piper
Project version: 0.5.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency pygobject-3.0 found: YES 3.36.0
Program ratbagd found: YES
Message: 
    *********************** WARNING ****************************
    *                 (   )(                                   *
    *         (\-.     ) (  )    ratbagd found in $PATH is too *
    *         / _`> .---------.  old and  will  not  work with *
    * _)     / _)=  |'-------'|  this version of Piper. Please *
    *(      / _/    |O   O   o|  update libratbag/ratbagd.     *
    * `-.__(___)_   | o O . o |                                *
    ************************************************************
    
Configuring piper.1 using configuration
Configuring AboutDialog.ui using configuration
WARNING: Gettext not found, all translation targets will be ignored.
Configuring org.freedesktop.Piper.appdata.xml.in using configuration
Program svgs/check-svg.py found: YES
Program svg-lookup-ini-test.py found: YES
Program check-svg-in-meson.build.sh found: YES
Program check-files-in-git.sh found: YES
Configuring piper.gresource.xml with command
Found pkg-config: /usr/bin/pkg-config (0.29.1)
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.46.0': Python Module.
WARNING: Project targeting '>= 0.42.0' but tried to use feature introduced in '0.51.0': modules arg in python.find_installation.
Program python3 (lxml, evdev, cairo, gi) found: YES (/usr/bin/python3) modules: lxml, evdev, cairo, gi
Configuring piper using configuration
Configuring piper.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/filipecunha/Documents/piper/meson_install.sh)
Program flake8 found: YES
Build targets in project: 1
WARNING: Project specifies a minimum meson_version '>= 0.42.0' but uses features which were added in newer versions:
 * 0.46.0: {'Python Module'}
 * 0.51.0: {'modules arg in python.find_installation'}

Found ninja-1.10.0 at /usr/bin/ninja
```

and nothing happened after this, was this the expected result?

**Comment by stephanlachnit** [comment]
You messed up your system with pip pretty hard, try to avoid it for build dependencies. It simply would have been
`sudo apt-get build-dep piper` (assuming you're on 20.04 or later).
Then
`meson builddir --prefix=/usr` and `meson install -C builddir`.

**Comment by muzena** [comment]
@FilipeCunha720 
https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git

**Comment by FilipeCunha720** [comment]
I follow @stephanlachnit advice and I ran this command `sudo apt-get build-dep piper`

I got this output

```
Reading package lists... Done
E: You must put some 'deb-src' URIs in your sources.list
```

I also ran this command `meson builddir --prefix=/usr` inside `piper` directory and got this output

```
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
```

I also ran this command `meson install -C builddir`

```
ninja: Entering directory `builddir'
ninja: no work to do.
Installing subdir /home/user/Documents/piper/piper to /usr/lib/python3.8/site-packages/piper
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Traceback (most recent call last):
  File "/home/user/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
```

I follow @muzena link and I ran 

```
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
sudo apt-get update
```
And saw no problems.

I also ran `ninja -C builddir` inside piper directory and got this output

```
ninja: Entering directory `builddir'
ninja: no work to do.
```

and after that, I ran `sudo ninja -C builddir install` inside piper directory and got this output

```
ninja: Entering directory `builddir'
[0/1] Installing files.
Traceback (most recent call last):
  File "/home/user/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-install 
/home/user/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

I'm totally lost now, is this working? Am I running the right commands? I was expecting some kind of UI to pop up, but I don't know if I'm using the right command.

**Comment by muzena** [comment]
@FilipeCunha720 
sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
sudo apt-get update
sudo apt install piper

**Comment by stephanlachnit** [comment]
> I follow @stephanlachnit advice and I ran this command `sudo apt-get build-dep piper`
> 
> I got this output
> 
> ```
> Reading package lists... Done
> E: You must put some 'deb-src' URIs in your sources.list
> ```

Ah, you only have the binary repositories enabled. Go to the Update Settings, there you can enable them via tickboxes (do it for main and universe/multiverse). Don't forget to `apt update` after that.

> I also ran this command `meson builddir --prefix=/usr` inside `piper` directory and got this output
> 
> ```
> Directory already configured.
> 
> Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
> If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
> to force Meson to regenerate.
> 
> If build failures persist, run "meson setup --wipe" to rebuild from scratch
> using the same options as passed when configuring the build.
> To change option values, run "meson configure" instead.
> ```

The build folder already exitst, so you need to either reconfigure it or simply delete it and start from scratch.
`rm -r builddir && meson builddir --prefix=/usr`

> I also ran this command `meson install -C builddir`
> 
> ```
> ninja: Entering directory `builddir'
> ninja: no work to do.
> Installing subdir /home/user/Documents/piper/piper to /usr/lib/python3.8/site-packages/piper
> Installation failed due to insufficient permissions.
> Attempting to use polkit to gain elevated privileges...
> Traceback (most recent call last):
>   File "/home/user/.local/bin/meson", line 5, in <module>
>     from mesonbuild.mesonmain import main
> ModuleNotFoundError: No module named 'mesonbuild'
> ```

Yeah looks like you messed up your python installation with pip. Uninstall all the things you installed with it for this and try again.
Btw, you need to run `sudo meson install -C builddir`.

> I follow @muzena link and I ran 
> 
> ```
> sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git
> sudo apt-get update
> ```
> And saw no problems.

It only adds a repo and doesn't do anything else for building Piper.

> I also ran `ninja -C builddir` inside piper directory and got this output
> 
> ```
> ninja: Entering directory `builddir'
> ninja: no work to do.
> ```
> 
> and after that, I ran `sudo ninja -C builddir install` inside piper directory and got this output
> 
> ```
> ninja: Entering directory `builddir'
> [0/1] Installing files.
> Traceback (most recent call last):
>   File "/home/user/.local/bin/meson", line 5, in <module>
>     from mesonbuild.mesonmain import main
> ModuleNotFoundError: No module named 'mesonbuild'
> FAILED: meson-install 
> /home/user/.local/bin/meson install --no-rebuild
> ninja: build stopped: subcommand failed.
> ```

Using `ninja build && ninja install` is equivalent to `meson install`.

> I'm totally lost now, is this working? Am I running the right commands? I was expecting some kind of UI to pop up, but I don't know if I'm using the right command. 

No, it isn't. Not trying to be offensive, but did you read the wiki on how to build or install it? Why don't you simply install it via apt? `sudo apt install piper`, that's enough to get it.

**Comment by muzena** [comment]
It seems that no one reads wiki.
It's already the 3rd or 4th user on Ubuntu with the same problem.
Like this #582

**Comment by stephanlachnit** [comment]
Closing due to inactivity (and this isn't really a "bug" anyway).

**Comment by xyz970** [comment]
> @FilipeCunha720 sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git sudo apt-get update sudo apt install piper

Thanks for your help sir.. finally my logitech G300s work on Linux
