### ISSUE TITLE
Error with started piper

### ISSUE THREAD

**Issue by ghost** [libratbag/piper#608]
I have an error

```~ piper

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:71:44: Invalid number for color value

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:72:44: Invalid number for color value

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:74:53: Invalid number for color value

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:75:53: Invalid number for color value

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:76:56: Invalid number for color value

(piper:15190): Gtk-WARNING **: 16:11:21.088: Theme parsing error: colors.css:77:65: Invalid number for color value
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
  File "/usr/lib/python3.6/site-packages/piper/application.py", line 18, in <module>
    from .window import Window
  File "/usr/lib/python3.6/site-packages/piper/window.py", line 22, in <module>
    from .mouseperspective import MousePerspective
  File "/usr/lib/python3.6/site-packages/piper/mouseperspective.py", line 19, in <module>
    from .buttonspage import ButtonsPage
  File "/usr/lib/python3.6/site-packages/piper/buttonspage.py", line 20, in <module>
    from .mousemap import MouseMap
  File "/usr/lib/python3.6/site-packages/piper/mousemap.py", line 20, in <module>
    from lxml import etree
ImportError: /usr/lib64/python3.6/site-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

OS: OpenSuse Leap 15.2
Installed from standard repositories

**Comment by FFY00** [comment]
That seems like a downstream issue of the OpenSuse lxml package, or potentially one of its dependencies, please report it to them :blush:
