### ISSUE TITLE
trying to disable a profile gives this error

### ISSUE THREAD

**Issue by kainatquaderee** [libratbag/piper#905]
**Information**

- `ratbagd` version (-0.17`):
- Piper version: 0.7
- Distribution: ubuntu 22.04
- Device: logitech g502 hero 
- Kernel version (ex. `uname -srmo`): `Linux 6.5.5-x64v1-xanmod1 x86_64 GNU/Linux`

**Describe the bug**
trying to delete a profile from piper gives this error ( crushes the piper)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 573, in disabled
    self._set_dbus_property("Disabled", "b", disabled)
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 223, in _set_dbus_property
    self._proxy.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)

**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

**Logs**
Please start the daemon with verbosity and reproduce the issue.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 573, in disabled
    self._set_dbus_property("Disabled", "b", disabled)
  File "/usr/lib/python3/dist-packages/piper/ratbagd.py", line 223, in _set_dbus_property
    self._proxy.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
OUTPUT HERE
```

**Additional context**

**Comment by staticssleever668** [comment]
Hi! This has been fixed in libratbag HEAD https://github.com/libratbag/libratbag/pull/1453
